// Package markdown renders an Incident as a postmortem-ready Markdown document
// suitable for pasting into an incident issue, wiki page, or PR description.
// The output is intentionally verbose — designed to be the complete evidence
// record, not a summary.
package markdown

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/rewind-io/rewind/internal/model"
)

// Render writes the incident as a Markdown document to w.
func Render(w io.Writer, inc model.Incident) error {
	r := &renderer{w: w, inc: inc}
	r.writeHeader()
	r.writeSources()
	r.writeTimeline()
	r.writeVerdict()
	r.writeFooter()
	return r.err
}

type renderer struct {
	w   io.Writer
	inc model.Incident
	err error
}

func (r *renderer) printf(format string, a ...any) {
	if r.err != nil {
		return
	}
	_, r.err = fmt.Fprintf(r.w, format, a...)
}

func (r *renderer) writeHeader() {
	dur := r.inc.Window.Duration().Round(time.Minute)
	r.printf("# Incident Report: %s\n\n", r.inc.ID)
	r.printf("| Field | Value |\n|---|---|\n")
	r.printf("| **Window** | `%s` → `%s` (%s) |\n",
		r.inc.Window.From.UTC().Format(time.RFC3339),
		r.inc.Window.To.UTC().Format(time.RFC3339),
		dur,
	)
	if len(r.inc.Scope.Namespaces) > 0 {
		r.printf("| **Namespace** | `%s` |\n", strings.Join(r.inc.Scope.Namespaces, ", "))
	}
	if len(r.inc.Scope.Services) > 0 {
		r.printf("| **Services** | `%s` |\n", strings.Join(r.inc.Scope.Services, ", "))
	}
	r.printf("| **Generated by** | rewind %s |\n\n", r.inc.Meta.RewindVersion)
}

func (r *renderer) writeSources() {
	if len(r.inc.Sources) == 0 {
		return
	}
	r.printf("## Data Sources\n\n")
	r.printf("| Source | Status | Duration | Events | Signals | Notes |\n")
	r.printf("|---|---|---|---|---|---|\n")
	for _, s := range r.inc.Sources {
		notes := ""
		if s.Error != "" {
			notes = "⚠ " + s.Error
		}
		if s.Endpoint != "" {
			notes = s.Endpoint
		}
		r.printf("| %s | %s | %s | %d | %d | %s |\n",
			s.Name, string(s.Status), s.Duration, s.EventCount, s.SignalCount, notes)
	}
	r.printf("\n")
}

func (r *renderer) writeTimeline() {
	r.printf("## Timeline\n\n")
	r.printf("| Time (UTC) | Severity | Type | Entity | Description |\n")
	r.printf("|---|---|---|---|---|\n")

	// Merge events and change-points, sorted by time.
	type row struct {
		at   time.Time
		sev  string
		typ  string
		ent  string
		desc string
	}
	var rows []row

	for _, e := range r.inc.Events {
		desc := e.Title
		if e.SourceRef.URL != "" {
			desc = fmt.Sprintf("[%s](%s)", e.Title, e.SourceRef.URL)
		}
		rows = append(rows, row{
			at:   e.At,
			sev:  string(e.Severity),
			typ:  string(e.Kind),
			ent:  "`" + e.EntityID + "`",
			desc: desc,
		})
	}
	for _, s := range r.inc.Signals {
		for _, cp := range s.ChangePoints {
			dir := "↑"
			if cp.Direction == model.DirectionDown {
				dir = "↓"
			}
			rows = append(rows, row{
				at:   cp.At,
				sev:  "Notable",
				typ:  "Anomaly",
				ent:  "`" + s.EntityID + "`",
				desc: fmt.Sprintf("%s%.1f× `%s` (confidence %.0f%%)", dir, cp.Magnitude, s.Metric, cp.Score*100),
			})
		}
	}

	// Sort by time.
	for i := 1; i < len(rows); i++ {
		for j := i; j > 0 && rows[j].at.Before(rows[j-1].at); j-- {
			rows[j], rows[j-1] = rows[j-1], rows[j]
		}
	}

	for _, row := range rows {
		r.printf("| `%s` | %s | %s | %s | %s |\n",
			row.at.UTC().Format("15:04:05"),
			row.sev, row.typ, row.ent, row.desc,
		)
	}
	r.printf("\n")
}

func (r *renderer) writeVerdict() {
	v := r.inc.Verdict
	if v == nil {
		return
	}
	r.printf("## Verdict\n\n")

	if v.NoTriggerFound || len(v.Hypotheses) == 0 {
		r.printf("**No clear trigger identified.**\n\n")
		if len(v.NotableAnomalies) > 0 {
			r.printf("Notable anomalies:\n\n")
			for _, a := range v.NotableAnomalies {
				r.printf("- %s\n", a)
			}
		}
		r.printf("\n")
		return
	}

	for i, h := range v.Hypotheses {
		trigger := h.TriggerEventID
		if e := model.EventByID(r.inc.Events, h.TriggerEventID); e != nil {
			trigger = e.Title
		}
		rank := "Hypothesis"
		if i == 0 {
			rank = "**Most Likely Hypothesis**"
		}
		r.printf("### %s %d — Confidence: `%s`\n\n", rank, i+1, h.Confidence)
		r.printf("**Trigger:** %s  \n", trigger)
		r.printf("**Rules:** %s  \n", strings.Join(h.RuleIDs, ", "))
		r.printf("**Explanation:** %s\n\n", h.Explanation)

		if len(h.Chain) > 0 {
			r.printf("**Causal chain:**\n\n")
			for j, link := range h.Chain {
				r.printf("%d. %s\n", j+1, link.Description)
			}
			r.printf("\n")
		}
	}
}

func (r *renderer) writeFooter() {
	r.printf("---\n\n")
	r.printf("*Generated by [rewind](https://github.com/rewind-io/rewind) %s at %s*\n",
		r.inc.Meta.RewindVersion,
		r.inc.Meta.CreatedAt.UTC().Format(time.RFC3339),
	)
}
